# -*- coding: utf-8 -*-
"""Missas Fortaleza.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b22Ozob8ReWzoo1twtb7GGy7A6MgSaFM
"""

import numpy as np

pip install tika

from tika import parser

import pandas as pd

raw = parser.from_file('/content/drive/MyDrive/Lumen/Missas Fortaleza/Missas.pdf')

content = raw['content']

editado = content.split('\n')

dados = [x.split(", '',") for x in editado]

df = pd.DataFrame(dados)

df = df[~df[0].str.contains('Áreas Pastorais e Santuários')]

df.to_csv(r'/content/drive/MyDrive/Lumen/Missas Fortaleza/Missas.csv')

"""Limpeza parte 2"""

df = pd.read_csv(r'/content/drive/MyDrive/Lumen/Missas Fortaleza/Missas - Página1.csv')

df.columns

df.loc[(df['Tipo'] =="Paróquia") | (df['Tipo'] =="-")]
df = df[['Info','Detalhe']]

df['Detalhe'].fillna(df['Info'], inplace=True)

array = np.array(df['Detalhe'])

new_shape = (151, 33)
reshaped_array = np.reshape(array, new_shape)

df_1 = pd.DataFrame(reshaped_array)

lista = df['Info'].head(33).tolist()

df_1.columns = lista

df_1.to_csv(r'/content/drive/MyDrive/Lumen/Missas Fortaleza/Final.csv', index=False)